import Head from "next/head";
import CategorySidebar from "@/components/categorySidebar";
import CTAButton from "@/components/CTAButton";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="article-wrapper">
          <CategorySidebar />
          <section style={{ display: "block", width: "100%", margin: "auto" }}>
            <CTAButton
              title="Åkturer"
              onClick={() => router.push("/attractions/Alla")}
            />
          </section>
        </section>
      </main>
    </>
  );
}
